[build]
  publish = "public"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-store"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/visuals/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/documentary/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/documentary/vendor/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
